name: Generate Build files for Next.js powered frontend
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          node-version: '16'
      
      # Build
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      
      # Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
      - uses: JamesIves/github-pages-deploy-action@4.4.0 
          with:
            branch: gh-pages
            folder: staticsite/out